// Code generated by ogen, DO NOT EDIT.

package ogencl

// APIClientInfoGetParams is parameters of GET /api/client/info operation.
type APIClientInfoGetParams struct {
	Ts string
}

// APIMessagePostParams is parameters of POST /api/message operation.
type APIMessagePostParams struct {
	Ts string
}

// APIMessageUUIDGetParams is parameters of GET /api/message/{uuid} operation.
type APIMessageUUIDGetParams struct {
	UUID string
	Ts   string
}
