generator:
  features:
    enable:
      - 'paths/client'
    disable:
      - 'paths/server'
      # Disables webhooks client generation
      - 'webhooks/client'
      # Disables webhooks server generation
      - 'webhooks/server'
      # Disables validation of server responses
      - 'ogen/otel'
      # Disables stub Handler generation
      - 'ogen/unimplemented'
      # Disables example tests generation
      - 'debug/example_tests'